### ISSUE TITLE
Tutorial error

### ISSUE THREAD

**Issue by yarkhunova** [YiliangTracyZhang/SUPERGNOVA#1]
Dear developers of Supergnova,

I am trying to run the tutorial script, but getting an error (see the output below), similar issue was reported on biostars biostars.org/p/9538520/

Could you please help us to resolve?

Thank you

Preparing files for analysis...
Traceback (most recent call last):
  File "supergnova.py", line 93, in <module>
    pipeline(parser.parse_args())
  File "supergnova.py", line 54, in pipeline
    gwas_snps, bed, N1, N2 = prep(args.bfile, args.partition, args.sumstats1, args.sumstats2, args.N1, args.N2)
  File "/Users/imacyy/SUPERGNOVA/prep.py", line 78, in prep
    allign_alleles(df)
  File "/Users/imacyy/SUPERGNOVA/prep.py", line 28, in allign_alleles
    df.where(pd.Series(((matched_alleles_x|reversed_alleles_x)&(matched_alleles_y|reversed_alleles_y))), inplace=True)
  File "/Users/imacyy/Library/Python/3.8/lib/python/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/Users/imacyy/Library/Python/3.8/lib/python/site-packages/pandas/util/_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
  File "/Users/imacyy/Library/Python/3.8/lib/python/site-packages/pandas/core/frame.py", line 11945, in where
    return super().where(
  File "/Users/imacyy/Library/Python/3.8/lib/python/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/Users/imacyy/Library/Python/3.8/lib/python/site-packages/pandas/util/_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
  File "/Users/imacyy/Library/Python/3.8/lib/python/site-packages/pandas/core/generic.py", line 9973, in where
    return self._where(cond, other, inplace, axis, level)
  File "/Users/imacyy/Library/Python/3.8/lib/python/site-packages/pandas/core/generic.py", line 9737, in _where
    self._check_inplace_setting(other)
  File "/Users/imacyy/Library/Python/3.8/lib/python/site-packages/pandas/core/generic.py", line 6023, in _check_inplace_setting
    raise TypeError(
TypeError: Cannot do inplace boolean setting on mixed-types with a non np.nan value

**Comment by qiyanghong2020** [comment]
Preparing files for analysis...
Traceback (most recent call last):
  File "/home/hongqy/workdir/local_genetic_correlation/SUPERGNOVA-master/supergnova.py", line 93, in <module>
    pipeline(parser.parse_args())
  File "/home/hongqy/workdir/local_genetic_correlation/SUPERGNOVA-master/supergnova.py", line 54, in pipeline
    gwas_snps, bed, N1, N2 = prep(args.bfile, args.partition, args.sumstats1, args.sumstats2, args.N1, args.N2)
  File "/home/hongqy/workdir/local_genetic_correlation/SUPERGNOVA-master/prep.py", line 78, in prep
    allign_alleles(df)
  File "/home/hongqy/workdir/local_genetic_correlation/SUPERGNOVA-master/prep.py", line 28, in allign_alleles
    df.where(pd.Series(((matched_alleles_x|reversed_alleles_x)&(matched_alleles_y|reversed_alleles_y))), inplace=True)
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 10955, in where
    return super().where(cond, other, inplace, axis, level, errors, try_cast)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 9308, in where
    return self._where(cond, other, inplace, axis, level, errors=errors)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 9144, in _where
    self._check_inplace_setting(other)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 5691, in _check_inplace_setting
    raise TypeError(
TypeError: Cannot do inplace boolean setting on mixed-types with a non np.nan value

**Comment by qiyanghong2020** [comment]
I fix  file "prep.py", line 28  with:
    df.where(pd.Series(((matched_alleles_x|reversed_alleles_x)&(matched_alleles_y|reversed_alleles_y))),**np.nan,** inplace=True)
after that not raise AttributeError anymore
